Properly handle corner cases
panicbit/quickcheck_derive pull request #4
Opened 2018-09-03 05:45 UTC by hcpl

For unit structs/variants make the `Gen` argument unused with a leading underscore.

For zero-variant enums the code previously generated `match g.gen_range(0, 0) { ... }` which panics according to https://docs.rs/rand/0.4.3/rand/trait.Rng.html#panics.

2018-09-03 06:59 UTC, panicbit requested changes
Looks good! There's one thing I'd like to have changed tho. Instead of generating `unimplemented!()` for enums without variants maybe we could panic in the macro with an appropriate error message?

2018-09-03 17:11 UTC, hcpl commented
I agree. Implementing `Arbitrary` for empty types is kind of pointless in most cases, so we can just error out right away like:
```rust
match s.variants().len() {
    0 => panic!("Cannot derive `Arbitrary` for an enum with no variants."),
    ...
}
```

And even if there may be cases when such types need an `impl Arbitrary` (e.g. to satisfy type constraints in a generic function), a manual impl is 5 lines anyway.

2018-09-04 19:14 UTC, hcpl commented
Sorry, forgot to push after commenting! :smile:

2018-09-04 20:18 UTC, panicbit approved these changes

2018-09-04 20:19 UTC, merged